name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: sairam-peruri
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist
