name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'  # Explicitly checkout the main branch

      # Step 2: Generate the Snake image using Platane/snk
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: sairam-peruri
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Step 3: Upload the generated images as an artifact
      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist
